# Generated by Django 5.2.14 on 2026-05-16 01:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason shown to the customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual refund amount (leave blank for no refund)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='refund_type',
            field=models.CharField(blank=True, choices=[('none', 'No Refund'), ('partial', 'Partial Refund'), ('full', 'Full Refund')], default='none', max_length=10),
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_type', models.CharField(choices=[('booking_received', 'Booking Received (customer)'), ('admin_notify', 'New Booking Notification (admin)'), ('booking_approved', 'Booking Approved (customer)'), ('booking_cancelled', 'Booking Cancelled (customer)')], max_length=30)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(max_length=300)),
                ('body_html', models.TextField()),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], default='sent', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='bookings.booking')),
                ('sent_by', models.ForeignKey(blank=True, help_text='Admin user who triggered the email (null = system)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_emails', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Log',
                'verbose_name_plural': 'Email Logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
