# Generated by Django 5.2.14 on 2026-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_emaillog_vendor_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='confirmation_number',
            field=models.CharField(blank=True, help_text='Auto-generated unique reference shown to the customer (e.g. AB-K3M7X9QP).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='email_type',
            field=models.CharField(choices=[('booking_received', 'Booking Received (customer)'), ('admin_notify', 'New Booking Notification (admin)'), ('booking_approved', 'Booking Approved (customer)'), ('booking_cancelled', 'Booking Cancelled (customer)'), ('cancel_request_customer', 'Cancellation Request (customer)'), ('cancel_request_admin', 'Cancellation Request (admin)'), ('vendor_received', 'New Booking Received (vendor)'), ('vendor_confirmed', 'Booking Confirmed (vendor)'), ('vendor_cancelled', 'Booking Cancelled (vendor)')], max_length=30),
        ),
    ]
