# Generated by Django 5.2.14 on 2026-05-29 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_vendor_notify_default_true'),
        ('terms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termsacceptance',
            name='version_at_acceptance',
            field=models.CharField(help_text='Snapshot of TermsOfUse.version at the time of acceptance.', max_length=50),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='content',
            field=models.TextField(help_text='HTML is supported. Keep it concise — the full text is shown in a scrollable box during booking.'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Enable to require acceptance during booking. Disable to stop showing this terms document without deleting it.'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Required when scope = Service-specific; ignored for Site-wide.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='services.service'),
        ),
        migrations.AlterField(
            model_name='termsofuse',
            name='version',
            field=models.CharField(help_text='e.g. v1.0 or 2024-01. Snapshot at acceptance time for audit.', max_length=50),
        ),
    ]
