# Generated by Django 5.2.14 on 2026-05-14 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('banquet_hall', 'Banquet Hall'), ('music_band', 'Music Band'), ('event_management', 'Event Management'), ('catering', 'Catering'), ('dancing', 'Dancing'), ('priests', 'Priests'), ('hotels', 'Hotels')], unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='ISO 2-letter code, e.g. IN', max_length=5, unique=True)),
                ('currency', models.CharField(default='INR', help_text='e.g. INR, USD', max_length=10)),
                ('currency_symbol', models.CharField(default='₹', max_length=5)),
                ('phone_code', models.CharField(default='+91', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('boolean', 'Yes/No'), ('text', 'Text'), ('number', 'Number'), ('choice', 'Choice')], default='boolean', max_length=20)),
                ('choices', models.TextField(blank=True, help_text='Comma-separated choices')),
                ('unit', models.CharField(blank=True, help_text='e.g. persons, hours', max_length=30)),
                ('is_filterable', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='services.category')),
            ],
            options={
                'ordering': ['order', 'name'],
                'unique_together': {('category', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='services.district')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('district', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('pin_code', models.CharField(blank=True, max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, help_text='Base price in local currency', max_digits=12)),
                ('price_unit', models.CharField(default='per event', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='services.category')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='services.city')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='services/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='services.service')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='State/Province code', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='services.country')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('country', 'name')},
            },
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='services.state'),
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, default='', max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='services.city')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.vendor'),
        ),
        migrations.CreateModel(
            name='ServiceAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_boolean', models.BooleanField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=500)),
                ('value_number', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.attributedefinition')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='services.service')),
            ],
            options={
                'unique_together': {('service', 'attribute')},
            },
        ),
        migrations.CreateModel(
            name='RegionalCategoryConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_unit_label', models.CharField(default='per event', help_text='Local label, e.g. "per event", "per night", "per plate"', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Any region-specific notes for admins')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_configs', to='services.category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_configs', to='services.country')),
                ('enabled_attributes', models.ManyToManyField(blank=True, help_text='Which attributes are shown/used for this category in this region', to='services.attributedefinition')),
                ('state', models.ForeignKey(blank=True, help_text='Leave blank for country-wide default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_configs', to='services.state')),
            ],
            options={
                'verbose_name': 'Regional Category Config',
                'unique_together': {('category', 'country', 'state')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('state', 'name')},
        ),
    ]
