# Generated by Django 5.2.14 on 2026-05-15 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_vendor_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name_plural': 'Cities'},
        ),
        migrations.AlterModelOptions(
            name='regionalcategoryconfig',
            options={'verbose_name': 'Regional Category Config', 'verbose_name_plural': 'Regional Category Configs'},
        ),
        migrations.AddField(
            model_name='regionalcategoryconfig',
            name='local_description',
            field=models.TextField(blank=True, help_text='Short description in the local language (shown on category cards/pages)'),
        ),
        migrations.AddField(
            model_name='regionalcategoryconfig',
            name='local_display_name',
            field=models.CharField(blank=True, help_text='Local name shown to users, e.g. "Purohit" instead of "Priests" in Telangana', max_length=100),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='name',
            field=models.CharField(help_text='Default English name', max_length=100),
        ),
        migrations.AlterField(
            model_name='regionalcategoryconfig',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin-only notes'),
        ),
        migrations.CreateModel(
            name='AttributeLocalName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_name', models.CharField(help_text='Name shown to users in this region', max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_names', to='services.attributedefinition')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.country')),
                ('state', models.ForeignKey(blank=True, help_text='Leave blank for country-wide override', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.state')),
            ],
            options={
                'verbose_name': 'Attribute Local Name',
                'unique_together': {('attribute', 'country', 'state')},
            },
        ),
    ]
