# Generated by Django 5.2.14 on 2026-05-15 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_alter_city_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text='Internal notes about this staff member')),
                ('city', models.ForeignKey(blank=True, help_text='Limit access to this city (overrides state)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.city')),
                ('country', models.ForeignKey(blank=True, help_text='Limit access to this country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.country')),
                ('state', models.ForeignKey(blank=True, help_text='Limit access to this state (overrides country)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.state')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
    ]
