# Generated by Django 5.2.14 on 2026-05-16 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_vendor_notify_on_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='city',
            name='image',
            field=models.ImageField(blank=True, upload_to='cities/'),
        ),
        migrations.AddField(
            model_name='city',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on home page city cards'),
        ),
    ]
