# Generated by Django 5.2.14 on 2026-05-29 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_vendor_user_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='notify_on_booking',
            field=models.BooleanField(default=True, help_text='Send email to this vendor when a booking is received, confirmed, or cancelled.'),
        ),
    ]
