# Generated by Django 5.2.14 on 2026-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_vendor_notify_default_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS latitude for location detection', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='GPS longitude for location detection', max_digits=9, null=True),
        ),
    ]
